#Stack: acme_wildcard

version: '3.6'
services:
  acme_wildcard:
    image: registry.staudigl.local:443/acme_wildcard:20190809
    volumes:
      - /var/lib/boot2docker/apps/letsencrypt:/certs
    environment:
      - 'SSL_AUTODEPLOY=false'          # Erstellt die Zertifikate beim Start des Containers
      - 'SSL_DOMAIN=staudigl-druck.de'  # Für welche Domain sollen die Zertifikate ausgestellt werden?
      - 'TESTRUN=true'                  # Sollen Demo Zertifikate ausgestellt werden?
      - 'MAIL_ADRESS=Email@adress.de'
      - 'PASSWORD=password'